<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtlYgb1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtlYgb1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUtlYgb1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUtlYgb1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUtlYgb1\App_KernelDevDebugContainer([
    'container.build_hash' => 'UtlYgb1',
    'container.build_id' => '1dd03538',
    'container.build_time' => 1576506941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtlYgb1');
